/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gdav1 from "./gdav1";
export type { gdav1 };
export type { IConstantFlowAgreementV1 } from "./IConstantFlowAgreementV1";
export type { IInstantDistributionAgreementV1 } from "./IInstantDistributionAgreementV1";
