/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export interface ISETHCustomInterface extends Interface {
  getFunction(
    nameOrSignature: "downgradeToETH" | "upgradeByETH" | "upgradeByETHTo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "downgradeToETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeByETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeByETHTo",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "downgradeToETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeByETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeByETHTo",
    data: BytesLike
  ): Result;
}

export interface ISETHCustom extends BaseContract {
  connect(runner?: ContractRunner | null): ISETHCustom;
  waitForDeployment(): Promise<this>;

  interface: ISETHCustomInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  downgradeToETH: TypedContractMethod<
    [wad: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeByETH: TypedContractMethod<[], [void], "payable">;

  upgradeByETHTo: TypedContractMethod<[to: AddressLike], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "downgradeToETH"
  ): TypedContractMethod<[wad: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeByETH"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "upgradeByETHTo"
  ): TypedContractMethod<[to: AddressLike], [void], "payable">;

  filters: {};
}
