/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BoardGame__factory } from "./BoardGame__factory";
export { MoneyRouter__factory } from "./MoneyRouter__factory";
