/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PlaceStructStruct = {
  x: BigNumberish;
  y: BigNumberish;
  color: string;
};

export type PlaceStructStructOutput = [x: bigint, y: bigint, color: string] & {
  x: bigint;
  y: bigint;
  color: string;
};

export interface BoardGameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "boards"
      | "canPlace"
      | "changeColor"
      | "currentWinColor"
      | "gameId"
      | "getBoard"
      | "getWinningColor"
      | "isUserWin"
      | "listOfColorUser"
      | "newGame"
      | "owner"
      | "place"
      | "removeAddress"
      | "renounceOwnership"
      | "sendLumpSumToContract"
      | "sharedPriceRate"
      | "startTime"
      | "stringCompare"
      | "superToken"
      | "transferOwnership"
      | "updateSuperToken"
      | "userColor"
      | "userLocation"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "Placed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "boards",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canPlace",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeColor",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "currentWinColor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gameId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBoard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinningColor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserWin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listOfColorUser",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "newGame", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "place",
    values: [BigNumberish, PlaceStructStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAddress",
    values: [BigNumberish, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendLumpSumToContract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sharedPriceRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stringCompare",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "superToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSuperToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userColor",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userLocation",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "boards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canPlace", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeColor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentWinColor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBoard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWinningColor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isUserWin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listOfColorUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "place", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendLumpSumToContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharedPriceRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stringCompare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "superToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSuperToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userColor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userLocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlacedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    user: AddressLike,
    x: BigNumberish,
    y: BigNumberish,
    color: string
  ];
  export type OutputTuple = [
    gameId: bigint,
    user: string,
    x: bigint,
    y: bigint,
    color: string
  ];
  export interface OutputObject {
    gameId: bigint;
    user: string;
    x: bigint;
    y: bigint;
    color: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BoardGame extends BaseContract {
  connect(runner?: ContractRunner | null): BoardGame;
  waitForDeployment(): Promise<this>;

  interface: BoardGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  boards: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish],
    [string],
    "view"
  >;

  canPlace: TypedContractMethod<[_gameId: BigNumberish], [boolean], "view">;

  changeColor: TypedContractMethod<
    [_gameId: BigNumberish, _color: string],
    [void],
    "nonpayable"
  >;

  currentWinColor: TypedContractMethod<[], [string], "view">;

  gameId: TypedContractMethod<[], [bigint], "view">;

  getBoard: TypedContractMethod<[_gameId: BigNumberish], [string[][]], "view">;

  getWinningColor: TypedContractMethod<
    [_gameId: BigNumberish],
    [string],
    "view"
  >;

  isUserWin: TypedContractMethod<[_gameId: BigNumberish], [boolean], "view">;

  listOfColorUser: TypedContractMethod<
    [arg0: BigNumberish, arg1: string, arg2: BigNumberish],
    [string],
    "view"
  >;

  newGame: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  place: TypedContractMethod<
    [_gameId: BigNumberish, input: PlaceStructStruct],
    [void],
    "nonpayable"
  >;

  removeAddress: TypedContractMethod<
    [_gameId: BigNumberish, _color: string, _addressToRemove: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sendLumpSumToContract: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  sharedPriceRate: TypedContractMethod<[], [bigint], "view">;

  startTime: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  stringCompare: TypedContractMethod<
    [_string1: string, _string2: string],
    [boolean],
    "view"
  >;

  superToken: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSuperToken: TypedContractMethod<
    [_superToken: AddressLike],
    [void],
    "nonpayable"
  >;

  userColor: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;

  userLocation: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawFunds: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "boards"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "canPlace"
  ): TypedContractMethod<[_gameId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "changeColor"
  ): TypedContractMethod<
    [_gameId: BigNumberish, _color: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentWinColor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gameId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBoard"
  ): TypedContractMethod<[_gameId: BigNumberish], [string[][]], "view">;
  getFunction(
    nameOrSignature: "getWinningColor"
  ): TypedContractMethod<[_gameId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isUserWin"
  ): TypedContractMethod<[_gameId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "listOfColorUser"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: string, arg2: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "newGame"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "place"
  ): TypedContractMethod<
    [_gameId: BigNumberish, input: PlaceStructStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAddress"
  ): TypedContractMethod<
    [_gameId: BigNumberish, _color: string, _addressToRemove: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendLumpSumToContract"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sharedPriceRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "startTime"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "stringCompare"
  ): TypedContractMethod<
    [_string1: string, _string2: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "superToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSuperToken"
  ): TypedContractMethod<[_superToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userColor"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "userLocation"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Placed"
  ): TypedContractEvent<
    PlacedEvent.InputTuple,
    PlacedEvent.OutputTuple,
    PlacedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Placed(uint256,address,uint256,uint256,string)": TypedContractEvent<
      PlacedEvent.InputTuple,
      PlacedEvent.OutputTuple,
      PlacedEvent.OutputObject
    >;
    Placed: TypedContractEvent<
      PlacedEvent.InputTuple,
      PlacedEvent.OutputTuple,
      PlacedEvent.OutputObject
    >;
  };
}
