/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20 from "./erc20";
export type { erc20 };
import type * as nft from "./nft";
export type { nft };
export type { BoardGame } from "./BoardGame";
export type { Greeter } from "./Greeter";
